### ISSUE TITLE
Generar Documento Requerimiento

### ISSUE THREAD

**Issue by StuardMS** [StuardMS/P-PV-COMEDOR#2]

**Comment by DraugCR** [comment]
El alcance del producto:
El sistema tendrá primeramente la funcionalidad de almacenar y consultar la información de un estudiante con su respectivo tipo de beca y status, por lo tanto, debe existir una pantalla en la cual se maneje la información de cada registro. El sistema debe registrar el usuario el cual administra en ese momento la aplicación, es decir, una pantalla en la cual se controle la información con su respectivo login

El valor del producto:
El producto permitirá la eliminación de tarjetas, lo cual es un costo menos para la institución y una reducción en la contaminación del ambiente, además reducirá lo que son la falsificación debido a que solo se dará permiso una vez por día a la persona con la beca

El público objetivo:
El público meta son todos los estudiantes e instituciones que cuenten con un sistema de becas de comedor, para que así lo cambien por unos automatizado, con registro diario y una base de datos, además de uno o varios admins según lo necesiten

El uso previsto:
El uso consta con una APP en la cual se deben registrar para almacenar la información de los estudiantes además de  la o las becas estas asignadas por los administradores. Una vez hecho esto, la APP cuenta con un QR el cual es escaneado por una persona en la entrada del comedor, a esta persona le mostrará si tiene beca y si ya fue registrado ese día, esto para evitar que se pasen el celular entre estudiantes, este QR mostrará la información de estudiante y el tipo de beca con la que cuenta,


Login para pantallas de admin y para el estudiante:

crear una base de datos con las siguientes tablas

- admin
nombre 
apellidos
correo
dirección

-estudiante
nombre
apellidos
edad
grado
correo 
dirección


generar UI de admin con los siguientes apartados

-consultar lista de estudiantes
nombre de estudiante
tipo de beca

-historial de uso diario de la app
nombre de estudiante 
tipo de beca

- historial de estudiantes que no utilizaron la app
nombre de estudiante
tipo de beca

-crear opción de ingreso manual de numero de carnet

-crear pantalla de registro de información
nombre
apellido
edad
grado
correo
dirección
