### ISSUE TITLE
Crear FE de formulario creación de carnet en QR 

### ISSUE THREAD

**Issue by StuardMS** [StuardMS/P-PV-COMEDOR#27]
Se adjunta material para la creación de qr desde java android
https://www.desarrollolibre.net/blog/android/como-crear-un-lector-de-codigos-qr-en-android-con-android-studio
https://www.youtube.com/watch?v=XE5GO-fMmDQ
https://parzibyte.me/blog/2018/04/24/leer-codigo-qr-android-java/

**Comment by BritanyMorales05** [comment]
@BritanyMorales05 
@marcocr26
