### ISSUE TITLE
Crear formulario FE lector QR

### ISSUE THREAD

**Issue by StuardMS** [StuardMS/P-PV-COMEDOR#29]
Adjunto material para la creación y lectura de QR que sería el carnet

https://www.desarrollolibre.net/blog/android/como-crear-un-lector-de-codigos-qr-en-android-con-android-studio
https://www.youtube.com/watch?v=XE5GO-fMmDQ
https://parzibyte.me/blog/2018/04/24/leer-codigo-qr-android-java/

**Comment by xavism06** [comment]
@EvelynSiezar18 
@xavism06
